name: NDK copy 

on:
  workflow_dispatch:

jobs:
  ndk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Copy NDK
      run: | 
            cp -R $ANDROID_NDK_HOME/* .
            rm $(find . -size +100M | tr '\n' ' ')

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: NDK
